name = "Seeds"
description = "Seeds is a regenerative financial system for a thriving global society. A global movement that aligns radical empowerment of purpose with finance with the mission to bring about a modern day Renaissance. Since its alpha release on November 5th 2019 and its public launch in March 2020, SEEDS has gathered 150+ alliance members from across multiple bioregions."
stars = 5
sectionID = 1
rank = 3
url = "https://www.consciousinternet.org/#/projects/seeds"
