name = "Solidaridad"
description = """Solidaridad accelerates solutions for more sustainable and more inclusive supply chains.
They work closely with farmers and partner with companies, financial institutions, governments, service providers, and knowledge institutions around them.
ThreeFold capacity will be deployed in a pilot program for cocoa farmers in Ghana, in locations owned and operated by Solidaridad and local service providers."""
stars = 5
url = "https://wiki.foundation.grid.tf/#/projects/solidaridad"
