name = "Cloud28+"
description = "Cloud28+ is the world's largest independent community promoting cloud service and knowledge sharing. it serves end customers, cloud service providers, solution providers, ISVs, systems integrators, distributors, and government entities dedicated to accelerating enterprise cloud adoption."
stars = 5
sectionID = 3
rank = 4
url = "https://wiki.threefold.io/#/cloud28"
